'''
An exception is an event which occurs during program execution
that disrupts the normal flow of the program. When Python
encounters a situation that it cannot cope with, it raises an exception.
'''
# this produces a traceback error because we cannot divide by 0
# Read the traceback message.

print(10/0)
#important: note the exact traceback exception name.

#What is the problem on line  13 & 14?
#x=5; a='apple'
#print (x+a)   #why will this fail?

#What is the problem on line 17 -18?
#my_list =[1,2,3]
#x = my_list[4]

# What is the problem on line 21?
#import ringaleveo
